export const LEVEL_COUNT = 3,
    INITIAL_BLOCKS = 6,
    UPDATE_PERIOD = 3000,
    RENDER_PERIOD = 15,
    BALL_RADIUS = 1 / 2,
    ANGLE_INVERSION_TRESHOLD = 0.3,

    BAR_WIDTH = 6,
    BAR_HEIGHT = 2,

    BAR_PERIOD = 20,
    BAR_SPEED = RENDER_PERIOD / BAR_PERIOD,

    BALL_PERIOD = 50,
    BALL_SPEED = RENDER_PERIOD / BALL_PERIOD,

    ROWS = 30,
    COLS = 40,

    BLOCK_SIDE = 1,
    BLOCK_REACH = 1,
    BLOCK_Y_LIMIT = ROWS / 2;

