parserOptions:
  ecmaVersion: 2017

extends:
  - eslint:recommended

env:
  es6: true

globals:
  require: true
  module: true

rules:
  semi:
    - warn
    - never

  quotes:
    - warn
    - single
    - avoidEscape: true

  space-before-function-paren:
    - warn
    - named: "never"

  prefer-const:
    - warn

  indent:
    - warn

  new-cap:
    - error

  no-new-wrappers:
    - error

  no-shadow:
    - error

  generator-star-spacing:
    - warn
    - before: true
      after: false

  comma-dangle:
    - warn
    - never

  curly:
    - warn
    - multi
    - consistent
