version = 1

[[annotations]]
path = [
  "**/.gitattributes",
  "**/README.md",
  ".github/**.yml",
  ".gitignore",
  ".node-version",
  "client/assets/.well-known/host-meta",
  "client/assets/robots.txt",
  "client/assets/sitemap.xml",
  "client/styles/**.scss",
  "code/**.ts",
  "config/*.json",
  "data/icon-libraries/**.json",
  "data/og-images/config.json",
  "data/translation/**.json",
  "package.json",
  "REUSE.toml",
  "tsconfig.json",

  # It seems appropriate to license the images separately, but they are not an important enough part of the software to justify that.
  "client/assets/images/**",
  "client/assets/svg-libraries/*.svg",
  "data/og-images/**.png",
  "data/og-images/**.svg",
  "data/svg-libraries",
]
SPDX-FileCopyrightText = "Ianis Vasilev <ianis@ivasilev.net>"
SPDX-License-Identifier = "Unlicense"

# The REUSE documentation suggests licensing generated files under CC0-1.0 with NONE as author.
# https://reuse.software/faq/#exclude-file
[[annotations]]
path = [
  "mocks/**",
  "package-lock.json",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
