name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v5
    - uses: nodenv/actions/node-version@v3
      id: nodenv
    - uses: actions/setup-node@v6
      with:
        node-version: "${{ steps.nodenv.outputs.node-version }}"
    - name: Install node dependencies
      run: npm ci --no-audit
    - name: Lint
      run: npm run lint
    - name: Run unit tests
      run: npm run test:unit
