name: Run tests

on: [push]

jobs:
  test:
    runs-on: 'ubuntu-24.04'

    steps:
    - uses: actions/checkout@v4
    - uses: nodenv/actions/node-version@v3
      id: nodenv
    - uses: actions/setup-node@v4
      with:
        node-version: "${{ steps.nodenv.outputs.node-version }}"
    - name: Install node dependencies
      run: npm ci
    - name: Run unit tests
      run: |
        npm run lint
        npm run test:unit
